spring:
  main.banner-mode: off
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/app_db
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  liquibase:
    change-log: classpath:db-migration/changelog-master.yml
    contexts: prod

security: # todo: change before PROD deploy
  salt: "salt"
  token-key: "token-key"
  token-ttl-in-millis: 86400000 # 24 hours